### PR TITLE
small fix: missing bracket in README.md

### PR DESCRIPTION
**Pull request by mercuriete**
the example of use of this connector is wrong.

Someone miss a bracket in the example so a copy, paste don't work because of syntax error.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by gunjpan** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Hello @mercuriete, thank you for your pull request. The changes looks good to me AFAICT. One of our CI builds did not pass, but that's almost certainly not related to this change. I think this is good to be landed.

@gunjpan I have restarted the CI to see if the failure was intermittent. I'll leave it up to you to follow up and land this patch.

**Comment by gunjpan** [comment]
@slnode test please

**Comment by gunjpan** [comment]
@bajtos : Just in case if you revisit this: the failures are due to missing `petID`. I've a task to refactor test cases: see #14

**Comment by gunjpan** [comment]
@mercuriete : To make things easier, I've included your fix in my PR#16, which was to extend upon changes requested by @rblalock in PR#5. 

Thank you for your contribution.  I'll close this in favor of PR#16.

**Comment by mercuriete** [comment]
sorry for dont answer
thank you very much for fixing this problem :)

**Pull request closed without merging**
