### PR TITLE
Use path.extname instead of path.parse

### PR DESCRIPTION
**Pull request by Amir-61**
* Use `path.extname` instead of `path.parse`

Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1058

/to: @rmg @bajtos 
/cc: @superkhau

### CODE REVIEW

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
LGTM

**Comment by rmg** [comment]
LGTM

**Comment by bajtos** [comment]
👏

**Pull request merged**
