### PR TITLE
Adding a Custom Swagger Client through options/settings

### PR DESCRIPTION
**Pull request by mrackappan**
### Description
Code to accept a custom swagger client.

#### Related issues
#23 

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mrackappan** [comment]
This PR is for issue: https://github.com/strongloop/loopback-connector-swagger/issues/23

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jstockdill-ebsco** [comment]
Any chance this change can be merged?

**Comment by loay** [comment]
@mrackappan Would it be possible to add a test case, so regressions could be caught in the future?
Thanks.

**Comment by mrackappan** [comment]
Ran into some sync issues, Will be creating a new PR.

**Pull request closed without merging**
