### PR TITLE
Update loopback to 3.x

### PR DESCRIPTION
**Pull request by Amir-61**
Created a `loopback-2.x` branch; however I do not have admin access to make it protected; @superkhau could you please make it protected? Thanks!

/to: @superkhau

### CODE REVIEW

**Comment by superkhau** [comment]
LGTM

I think we should create a follow up issue to use Juggler directly for tests instead of LoopBack. @bajtos Thoughts?

**Comment by Amir-61** [comment]
@slnode test please

**Comment by superkhau** [comment]
Spoke with @rmg and @Amir-61 regarding Node 10 failure, it's legit and we need a follow issue for Object.parse/path.parse to fix it. @Amir-61 Please create an issue as assign to FA owners, TOB/Major. I override and merge this time.

**Comment by Amir-61** [comment]
Created a ticket for failure in Node 10: https://github.com/strongloop-internal/scrum-loopback/issues/1058

**Comment by superkhau** [comment]
@Amir-61 TY, merging.

**Comment by rmg** [comment]
It shouldn't be necessary to backlog an issue for a trivial two line change. You just have to replace `path.parse()` with `path.extname()`.

**Comment by bajtos** [comment]
> I think we should create a follow up issue to use Juggler directly for tests instead of LoopBack.

That does not make sense to me. loopback-swagger requires strong-remoting metadata describing the REST API, it won't work with vanilla juggler models.

**Comment by bajtos** [comment]
> It shouldn't be necessary to backlog an issue for a trivial two line change. You just have to replace `path.parse()` with `path.extname()`.

+1 ✖️ 💯 

We should have enough buffer in our estimates to allow us to make small fixes like this one on the fly.

**Comment by Amir-61** [comment]
Fixed with [PR#10](https://github.com/strongloop/loopback-connector-swagger/pull/10)

**Pull request merged**
