### PR TITLE
adding swagger client using option

### PR DESCRIPTION
**Pull request by mrackappan**
### Description
Code to accept a custom swagger client.

#### Related issues

#23

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mrackappan** [comment]
Commit Linter failed not being able to fetch the repo

**Pull request closed without merging**
